spring:
  application:
    name: BatchSample

  batch:
    jdbc:
      initialize-schema: always # Batch 메타데이터 테이블을 자동 생성
    job:
      enabled: true

  datasource:
    batch-metadata:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
      platform: h2
    business:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/businessdb
      username: root
      password: rootPWD
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # HikariCP 설정
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 5
